/**
 * LLM-powered diagram generation.
 * @deprecated Use callLlm from provider.ts + parseLlmResponse from prompts.ts directly.
 * Kept for backward compatibility with programmatic imports.
 */

import { generateDiagram } from "./svg";
import { DIAGRAM_PROMPT, parseLlmResponse, type DiagramSuggestion } from "./prompts";
import { callLlm } from "./provider";

export interface DescribeResult {
  suggestions: DiagramSuggestion[];
  raw: string;
}

export interface AutoResult {
  generated: Array<{
    filename: string;
    type: string;
    description: string;
    purpose: string;
    nodeCount: number;
    edgeCount: number;
  }>;
  outputDir: string;
}

export async function describeDiagrams(
  paperText: string,
  options?: { type?: "pipeline" | "architecture" | "flowchart" }
): Promise<DescribeResult> {
  let userPrompt = `Paper text:\n\n${paperText}`;
  if (options?.type) {
    userPrompt += `\n\nFocus on ${options.type} diagrams specifically.`;
  }

  const raw = await callLlm(DIAGRAM_PROMPT, userPrompt);
  const suggestions = parseLlmResponse(raw);

  const filtered = options?.type
    ? suggestions.filter((s) => s.type === options.type)
    : suggestions;

  return {
    suggestions: filtered.length > 0 ? filtered : suggestions,
    raw,
  };
}

export async function autoGenerateDiagrams(
  paperText: string,
  outputDir: string,
  options?: { type?: "pipeline" | "architecture" | "flowchart" }
): Promise<AutoResult> {
  const fs = await import("fs");
  const path = await import("path");

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const { suggestions } = await describeDiagrams(paperText, options);
  const generated: AutoResult["generated"] = [];

  for (let i = 0; i < suggestions.length; i++) {
    const s = suggestions[i];
    const result = generateDiagram(s.description, { type: s.type });

    const slug = s.purpose
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 40);
    const filename = `${String(i + 1).padStart(2, "0")}-${s.type}-${slug}.svg`;
    const filepath = path.join(outputDir, filename);

    fs.writeFileSync(filepath, result.svg);

    generated.push({
      filename,
      type: s.type,
      description: s.description,
      purpose: s.purpose,
      nodeCount: result.nodes.length,
      edgeCount: result.edges.length,
    });
  }

  return { generated, outputDir };
}
